
- name:
  block:
    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      tags:
        - install

    - name: Create directory for the app
      ansible.builtin.file:
        name: "{{ app_directory }}/"
        state: directory

    - name: Deploy compose.yaml
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: "{{ app_directory }}/compose.yaml"

    - name: Start the app
      community.docker.docker_compose_v2:
        project_src: "{{ app_directory }}"
        state: present

- name: Wipe
  import_tasks: 0-wipe.yml
  tags:
    - wipe
  when: wipe