- name: Deploy go web application
  hosts: all
  become: true

  roles:
    - web_app
  vars:
    docker_image: "nad777/anton_nekhaev_go"
    docker_tag: "latest"
    container_name: "web_app"
    app_directory: "app"
    exposed_port: "5001"