name: Python App CI

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'app_python/**'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'app_python/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
             ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies and Linter
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f app_python/requirements.txt ]; then pip install -r app_python/requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 app_python --max-line-length=101

      - name: Test with pytest
        run: |
          pytest app_python/tests/*.py
  
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker:
    needs: [build-and-test, security]
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:app_python/"
          push: true
          tags: nad777/anton_nekhaev_flask:latest